name: build

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:

  build-linux-amd64:
    name: Build - Linux amd64
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.90"
          override: true
          default: true
          profile: minimal
          target: x86_64-unknown-linux-musl
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=x86_64-unknown-linux-musl
          use-cross: true
      - name: Exec chmod
        run: chmod -v a+x target/x86_64-unknown-linux-musl/release/*
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-linux-amd64
          path: |
            target/x86_64-unknown-linux-musl/release/hbbs
            target/x86_64-unknown-linux-musl/release/hbbr
            target/x86_64-unknown-linux-musl/release/rustdesk-utils
          if-no-files-found: error

  build-windows-amd64:
    name: Build - Windows amd64
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.90"
          override: true
          default: true
          profile: minimal
          target: x86_64-pc-windows-msvc
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=x86_64-pc-windows-msvc
          use-cross: true
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-windows-amd64
          path: |
            target/x86_64-pc-windows-msvc/release/hbbs.exe
            target/x86_64-pc-windows-msvc/release/hbbr.exe
            target/x86_64-pc-windows-msvc/release/rustdesk-utils.exe
          if-no-files-found: error

  build-macos-amd64:
    name: Build - macOS amd64
    runs-on: macos-12
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.90"
          override: true
          default: true
          profile: minimal
          target: x86_64-apple-darwin
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features --target=x86_64-apple-darwin
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server-macos-amd64
          path: |
            target/x86_64-apple-darwin/release/hbbs
            target/x86_64-apple-darwin/release/hbbr
            target/x86_64-apple-darwin/release/rustdesk-utils
          if-no-files-found: error
